"""Holdet.dk public fantasy-data scraper."""

from .errors import (
    FetchError,
    PayloadError,
    ScraperError,
    UnsupportedGameError,
    UrlValidationError,
)
from .flight import extract_flight_text, iter_flight_values, walk_flight
from .http import (
    DEFAULT_CONNECTION_REFUSED_RETRIES,
    DEFAULT_RETRIES,
    DEFAULT_TIMEOUT_SECONDS,
    TRANSIENT_HTTP_STATUSES,
    USER_AGENT,
    HttpClient,
    fetch_html,
)
from .models import (
    AccountConfig,
    GameUrl,
    PlayerEntry,
    RosterEntry,
    RoundStatus,
    RoundSummary,
    ScheduleRound,
    ScrapedGame,
    ScrapedTeam,
    TeamOverview,
    TeamReference,
)
from .policies import (
    KNOWN_GAME_FORMATS,
    KNOWN_ROUTE_VARIANTS,
    ROUTE_VARIANT_FORMATS,
    VALUE_UNITS,
    GamePolicy,
    format_for_variant,
    legacy_policy,
    policy_from_ruleset,
)
from .players import (
    EXCLUDED_VARIANTS,
    SORT_FIELDS,
    SORT_ORDERS,
    SUPPORTED_HOSTS,
    SUPPORTED_VARIANTS,
    discover_variant,
    extract_entries_and_round,
    format_entry,
    format_integer,
    normalize_game_url,
    scrape_game,
    sort_entries,
)

from .accounts import (
    AccountStore,
    account_key_from_label,
    rename_account_and_groups,
)
from .client import HoldetClient
from .paths import APP_NAME, AppPaths, PathOverrides, open_in_explorer, resolve_paths
from .groups import (
    GROUP_SCHEMA_VERSION,
    GroupDefinition,
    HubConfiguration,
    GroupStore,
    GroupTeam,
    ManagerGame,
    TournamentRevision,
    group_team_from_snapshot,
    normalize_manager_game,
)
from .standings import StandingRow, build_standings
from .refresh import (
    GameRefreshResult,
    GroupRefreshResult,
    TeamRefresh,
    refresh_game,
    refresh_group,
)
from .tournament import (
    STAGE_NAMES,
    GroupFixture,
    GroupMatch,
    HeadToHeadMatch,
    HeadToHeadSummary,
    KnockoutMatch,
    TournamentConfig,
    TournamentStanding,
    TournamentState,
    bracket_seed_order,
    build_tournament_head_to_head,
    build_tournament_state,
    create_tournament_config,
    generate_draw_seed,
    generate_group_fixtures,
    knockout_size_for,
    latest_tournament_round,
    tournament_schedule_signature,
    validate_tournament_config,
)
from .output import (
    format_change,
    format_team_text,
    format_value,
    sanitize_path_component,
    team_to_dict,
)
from .serialization import SCHEMA_VERSION, team_from_dict, team_to_json
from .player_serialization import (
    PLAYER_STATISTICS_SCHEMA_VERSION,
    player_statistics_from_dict,
    player_statistics_to_dict,
    player_statistics_to_json,
)
from .player_exports import (
    MISSING_VALUE_MODES,
    PLAYER_COLUMNS,
    PLAYER_EXPORT_FORMATS,
    PLAYER_EXPORT_SCHEMA_VERSION,
    PLAYER_SORT_FIELDS,
    PLAYER_STATUSES,
    STATUS_LABELS_DA,
    STATUS_RULES,
    PlayerExportArtifact,
    PlayerExportDocument,
    PlayerExportStore,
    PlayerStatisticsQuery,
    build_player_export,
    entry_statuses,
    filter_player_statistics,
    format_player_status,
    player_column_labels,
    player_display_rows,
    player_export_to_dict,
    player_export_to_markdown,
    player_export_to_txt,
    player_query_to_dict,
    player_row,
    serialize_player_export,
)
from .team_exports import (
    TEAM_EXPORT_FORMATS,
    TEAM_EXPORT_SCHEMA_VERSION,
    TEAM_EXPORT_SCOPES,
    TeamExportArtifact,
    TeamExportDocument,
    TeamExportStore,
    build_team_export,
    serialize_team_export,
    team_export_to_dict,
    team_export_to_markdown,
    team_export_to_txt,
)
from .storage import (
    ManifestStore,
    PlayerStatisticsIndex,
    PlayerStatisticsSnapshot,
    PlayerStatisticsStore,
    SnapshotIndex,
    SnapshotStore,
    TeamSnapshot,
)
from .teams import (
    GameContext,
    TeamDataService,
    discover_profile_teams,
    extract_team_page,
    filter_team_references,
    load_accounts,
    parse_account_profile_user_id,
    parse_direct_team_url,
    parse_game_context,
    parse_game_display_name,
    parse_history,
    parse_schedule_final_round,
    parse_schedule_rounds,
    round_status_for,
    select_accounts,
)
from .analytics import (
    DataQualityReport,
    DataQualityRound,
    HistoryPoint,
    PlayerHistoryPoint,
    PlayerSnapshotChange,
    SnapshotDiff,
    TeamRankChange,
    TeamSnapshotDiff,
    build_data_quality_report,
    build_history_series,
    build_player_history,
    compare_round_snapshots,
    compare_snapshots,
    compare_team_rounds,
    compare_team_snapshots,
    latest_snapshot_diff,
)
from .backup import (
    BACKUP_SCHEMA_VERSION,
    BackupManifest,
    BackupManifestEntry,
    BackupValidation,
    RestoreResult,
    create_backup,
    create_backup_bytes,
    restore_backup,
    validate_backup,
)
from .game_metadata import (
    GAME_METADATA_SCHEMA_VERSION,
    GameMetadata,
    GameMetadataStore,
    game_metadata_from_context,
)
from .hall_of_fame import (
    HALL_OF_FAME_EVENT_SCHEMA_VERSION,
    HallOfFame,
    HallOfFameEvent,
    HallOfFamePlacement,
    HallOfFameRow,
    HallOfFameStore,
    build_hall_of_fame,
    build_live_hall_of_fame_events,
)
from .hub_settings import (
    HUB_SETTINGS_SCHEMA_VERSION,
    HallOfFameScoreProfile,
    HubSettings,
    HubSettingsStore,
    ManagerAlias,
    WatchlistEntry,
    manager_identity_keys,
    player_identity,
    resolve_manager_identity,
    watchlist_entry,
)
from .transfers import (
    CYCLING_RULES,
    FOOTBALL_RULES,
    GOLF_RULES,
    MOTOR_RULES,
    UNKNOWN_RULES,
    ScenarioPlayer,
    TransferRuleProfile,
    TransferScenario,
    TransferValidation,
    simulate_transfers,
    transfer_rule_profile,
)

from .version import VERSION

__all__ = [
    "VERSION",
    "AccountConfig", "AccountStore", "AppPaths", "FetchError", "GamePolicy",
    "GameUrl", "HoldetClient", "PathOverrides", "PayloadError", "PlayerEntry",
    "RosterEntry", "RoundStatus", "RoundSummary", "ScheduleRound", "ScrapedGame",
    "ScrapedTeam", "ScraperError",
    "TeamOverview", "TeamReference", "UnsupportedGameError", "UrlValidationError",
    "GroupDefinition", "GroupStore", "GroupTeam", "HubConfiguration", "ManagerGame",
    "TournamentConfig", "TournamentRevision", "TournamentState",
    "ManifestStore", "PlayerStatisticsIndex", "PlayerStatisticsStore",
    "SnapshotIndex", "SnapshotStore", "TeamSnapshot",
    "PlayerExportArtifact", "PlayerExportDocument", "PlayerExportStore",
    "PlayerStatisticsQuery", "TeamExportArtifact", "TeamExportDocument",
    "TeamExportStore", "build_player_export", "build_team_export",
    "build_standings", "build_tournament_head_to_head", "build_tournament_state",
    "create_tournament_config", "filter_player_statistics", "normalize_game_url",
    "normalize_manager_game", "player_statistics_from_dict",
    "player_statistics_to_dict", "player_statistics_to_json", "refresh_game",
    "refresh_group", "resolve_paths", "serialize_player_export",
    "BackupManifest", "BackupManifestEntry", "BackupValidation",
    "RestoreResult", "DataQualityReport", "DataQualityRound", "HistoryPoint",
    "PlayerHistoryPoint", "PlayerSnapshotChange", "SnapshotDiff",
    "TeamRankChange", "TeamSnapshotDiff", "GameMetadata", "GameMetadataStore",
    "HubSettings", "HubSettingsStore", "ManagerAlias", "WatchlistEntry",
    "HallOfFame", "HallOfFameEvent", "HallOfFamePlacement", "HallOfFameRow",
    "HallOfFameScoreProfile", "HallOfFameStore", "ScenarioPlayer",
    "TransferRuleProfile", "TransferScenario", "TransferValidation",
    "CYCLING_RULES", "FOOTBALL_RULES", "GOLF_RULES", "MOTOR_RULES",
    "UNKNOWN_RULES", "build_data_quality_report", "build_hall_of_fame",
    "build_history_series", "build_live_hall_of_fame_events",
    "build_player_history", "compare_round_snapshots", "compare_snapshots",
    "compare_team_rounds", "compare_team_snapshots", "create_backup",
    "create_backup_bytes", "game_metadata_from_context", "latest_snapshot_diff",
    "manager_identity_keys", "player_identity", "resolve_manager_identity",
    "restore_backup", "simulate_transfers", "transfer_rule_profile",
    "validate_backup", "watchlist_entry",

    "serialize_team_export", "team_from_dict", "team_to_json",
]