"""Holdet.dk public fantasy-data scraper."""

from .errors import (
    FetchError,
    PayloadError,
    ScraperError,
    UnsupportedGameError,
    UrlValidationError,
)
from .flight import extract_flight_text, iter_flight_values, walk_flight
from .http import (
    DEFAULT_CONNECTION_REFUSED_RETRIES,
    DEFAULT_RETRIES,
    DEFAULT_TIMEOUT_SECONDS,
    TRANSIENT_HTTP_STATUSES,
    USER_AGENT,
    HttpClient,
    fetch_html,
)
from .models import (
    AccountConfig,
    GameUrl,
    PlayerEntry,
    RosterEntry,
    RoundStatus,
    RoundSummary,
    ScheduleRound,
    ScrapedGame,
    ScrapedTeam,
    TeamOverview,
    TeamReference,
)
from .policies import (
    KNOWN_GAME_FORMATS,
    KNOWN_ROUTE_VARIANTS,
    ROUTE_VARIANT_FORMATS,
    VALUE_UNITS,
    GamePolicy,
    format_for_variant,
    legacy_policy,
    policy_from_ruleset,
)
from .players import (
    EXCLUDED_VARIANTS,
    SORT_FIELDS,
    SORT_ORDERS,
    SUPPORTED_HOSTS,
    SUPPORTED_VARIANTS,
    discover_variant,
    extract_entries_and_round,
    format_entry,
    format_integer,
    normalize_game_url,
    scrape_game,
    sort_entries,
)

from .accounts import (
    AccountStore,
    account_key_from_label,
    rename_account_and_groups,
)
from .client import HoldetClient
from .paths import APP_NAME, AppPaths, PathOverrides, open_in_explorer, resolve_paths
from .groups import (
    GROUP_SCHEMA_VERSION,
    GroupDefinition,
    HubConfiguration,
    GroupStore,
    GroupTeam,
    ManagerGame,
    TournamentRevision,
    group_team_from_snapshot,
    normalize_manager_game,
    validate_official_group_url,
)
from .standings import StandingRow, build_standings
from .refresh import (
    DAILY_REFRESH_MAX_AGE,
    GameRefreshResult,
    GroupRefreshResult,
    MetadataRefresh,
    ManifestWriteError,
    PlayerRefresh,
    RefreshMode,
    RefreshPlan,
    RefreshProgressCallback,
    RefreshProgressEvent,
    RefreshStep,
    TeamRefresh,
    build_refresh_plan,
    refresh_game,
    refresh_group,
    refresh_manager_game,
)
from .tournament import (
    STAGE_NAMES,
    GroupFixture,
    GroupMatch,
    HeadToHeadMatch,
    HeadToHeadSummary,
    KnockoutMatch,
    TournamentConfig,
    TournamentStanding,
    TournamentState,
    bracket_seed_order,
    build_tournament_head_to_head,
    build_tournament_state,
    create_tournament_config,
    generate_draw_seed,
    generate_group_fixtures,
    knockout_size_for,
    latest_tournament_round,
    tournament_schedule_signature,
    validate_tournament_config,
)
from .output import (
    format_change,
    format_team_text,
    format_value,
    sanitize_path_component,
    team_to_dict,
)
from .serialization import SCHEMA_VERSION, team_from_dict, team_to_json
from .player_serialization import (
    PLAYER_STATISTICS_SCHEMA_VERSION,
    player_statistics_from_dict,
    player_statistics_to_dict,
    player_statistics_to_json,
)
from .player_exports import (
    MISSING_VALUE_MODES,
    PLAYER_COLUMNS,
    PLAYER_EXPORT_FORMATS,
    PLAYER_EXPORT_SCHEMA_VERSION,
    PLAYER_SORT_FIELDS,
    PLAYER_STATUSES,
    STATUS_LABELS_DA,
    STATUS_RULES,
    PlayerExportArtifact,
    PlayerExportDocument,
    PlayerExportStore,
    PlayerStatisticsQuery,
    build_player_export,
    entry_statuses,
    filter_player_statistics,
    format_player_status,
    player_column_labels,
    player_display_rows,
    player_export_to_dict,
    player_export_data_package,
    player_export_to_markdown,
    player_export_to_txt,
    player_query_to_dict,
    player_query_from_dict,
    player_row,
    serialize_player_export,
)
from .team_exports import (
    TEAM_EXPORT_FORMATS,
    TEAM_EXPORT_SCHEMA_VERSION,
    TEAM_EXPORT_SCOPES,
    TeamExportArtifact,
    TeamExportDocument,
    TeamExportStore,
    build_team_export,
    serialize_team_export,
    team_export_data_package,
    team_export_to_dict,
    team_export_to_markdown,
    team_export_to_txt,
)
from .storage import (
    ManifestStore,
    PlayerStatisticsIndex,
    PlayerStatisticsSnapshot,
    PlayerStatisticsStore,
    RefreshManifest,
    RefreshManifestStep,
    RefreshMetadataChange,
    SnapshotIndex,
    SnapshotStore,
    TeamSnapshot,
)
from .teams import (
    GameContext,
    TeamDataService,
    discover_profile_teams,
    extract_team_page,
    filter_team_references,
    load_accounts,
    parse_account_profile_user_id,
    parse_direct_team_url,
    parse_game_context,
    parse_game_display_name,
    parse_history,
    parse_schedule_final_round,
    parse_schedule_rounds,
    round_status_for,
    select_accounts,
)
from .analytics import (
    DataQualityReport,
    DataQualityRound,
    HistoryPoint,
    PlayerHistoryPoint,
    PlayerSnapshotChange,
    SnapshotDiff,
    TeamRankChange,
    TeamSnapshotDiff,
    build_data_quality_report,
    build_history_series,
    build_player_history,
    compare_round_snapshots,
    compare_snapshots,
    compare_team_rounds,
    compare_team_snapshots,
    latest_snapshot_diff,
)
from .backup import (
    BACKUP_SCHEMA_VERSION,
    BackupManifest,
    BackupManifestEntry,
    BackupValidation,
    RestoreResult,
    create_backup,
    create_backup_bytes,
    restore_backup,
    validate_backup,
)
from .data_packages import (
    DATA_PACKAGE_SCHEMA_VERSION,
    TABULAR_EXPORT_FORMATS,
    DataPackage,
    DataTable,
    SerializedPackage,
    neutralize_spreadsheet_text,
    package_to_csv,
    package_to_dict,
    package_to_parquet,
    package_to_xlsx,
    serialize_data_package,
    table_to_csv,
)
from .sport_adapters import (
    SportAdapter,
    SportCapabilities,
    get_sport_adapter,
    registered_sport_adapters,
)
from .privacy import (
    ANONYMIZATION_PROFILES,
    anonymize_data_package,
    build_support_bundle,
)
from .reports import (
    REPORT_SCHEMA_VERSION,
    ReportArtifact,
    ReportStore,
    build_manager_game_report_package,
    build_season_report_package,
    render_html_report,
    render_round_story_html,
    round_story_html_filename,
)
from .imports import (
    ImportOperation,
    ImportPreview,
    ImportResult,
    apply_import,
    preview_import,
)
from .integrity import (
    INTEGRITY_INDEX_SCHEMA_VERSION,
    IntegrityCheck,
    IntegrityEntry,
    IntegrityIssue,
    IntegrityRepairPreview,
    full_integrity_check,
    preview_integrity_repair,
    quick_integrity_check,
    repair_integrity_index,
)
from .maintenance import (
    ArchiveResult,
    CleanupCandidate,
    RetentionCandidate,
    RetentionPlan,
    StorageInventory,
    StorageUsage,
    archive_retention_candidates,
    build_storage_inventory,
    delete_derived_files,
    list_cleanup_candidates,
    plan_snapshot_retention,
)
from .local_api import (
    LOCAL_API_DATASETS,
    LOCAL_API_VERSION,
    ApiQueryError,
    DatasetDefinition,
    LocalDataApi,
    RegisteredArtifact,
    dataset_catalog,
    register_artifact,
    resolve_registered_artifact,
)
from .game_metadata import (
    GAME_METADATA_SCHEMA_VERSION,
    GAME_METADATA_REVISION_SCHEMA_VERSION,
    GameMetadata,
    GameMetadataRevision,
    GameMetadataStore,
    MetadataChange,
    compare_game_metadata,
    game_metadata_from_context,
)
from .fixtures import (
    FIXTURE_CACHE_SCHEMA_VERSION,
    FixtureRecord,
    FixtureSnapshot,
    FixtureSourceProfile,
    FixtureStore,
    parse_fixture_records,
)
from .hall_of_fame import (
    HALL_OF_FAME_EVENT_SCHEMA_VERSION,
    HallOfFame,
    HallOfFameEvent,
    HallOfFamePlacement,
    HallOfFameRow,
    HallOfFameStore,
    build_hall_of_fame,
    build_live_hall_of_fame_events,
    remap_manager_events,
)
from .hub_settings import (
    DEFAULT_PLAYER_TAGS,
    HUB_SETTINGS_SCHEMA_VERSION,
    HallOfFameScoreProfile,
    HubSettings,
    HubSettingsStore,
    ManagerAlias,
    ManagerProfile,
    OwnTeamSelection,
    PlayerAnnotation,
    SavedPlayerFilter,
    WatchlistEntry,
    build_effective_manager_settings,
    manager_identity_keys,
    player_identity,
    resolve_manager_identity,
    watchlist_entry,
)
from .rules import (
    AUDITED_RULE_PROFILES,
    AnalysisCertainty,
    AnalysisProvenance,
    GameRuleProfile,
    game_rule_from_dict,
    game_rule_to_dict,
    rule_profile_for_game,
)
from .analysis_inbox import (
    ANALYSIS_INBOX_SCHEMA_VERSION,
    AnalysisInboxStore,
    WatchlistAlert,
    build_watchlist_alerts,
    select_alert_baseline,
)
from .decision_analysis import (
    BankAnalysis,
    CaptainAlternative,
    CaptainAnalysis,
    ExposureRow,
    GroupComparison,
    GroupExposure,
    IdealTeamResult,
    PlayerDecisionAnalysis,
    SimulationResult,
    TeamDecisionLedger,
    TransferDecision,
    build_bank_analysis,
    build_captain_analysis,
    build_group_comparison,
    build_group_exposure,
    build_player_decision_analysis,
    build_team_decision_ledger,
    optimize_ideal_team,
    simulate_transfer_scenario,
)
from .transfers import (
    CYCLING_RULES,
    FOOTBALL_RULES,
    GOLF_RULES,
    MOTOR_RULES,
    UNKNOWN_RULES,
    ScenarioPlayer,
    TransferRuleProfile,
    TransferScenario,
    TransferValidation,
    simulate_transfers,
    transfer_rule_profile,
)

from .calendar import CalendarEvent, build_calendar_events
from .manager_features import (
    HeadToHeadMeeting,
    ManagerCareer,
    ManagerEvent,
    ManagerHeadToHead,
    ManagerRating,
    ManagerRoundResult,
    RoundAward,
    RoundStoryFact,
    RoundStory,
    RoundStoryTeamRef,
    build_manager_careers,
    build_manager_head_to_head,
    build_manager_ratings,
    build_manager_round_results,
    build_round_awards,
    build_round_story,
    manager_events_from_hall_of_fame,
)
from .round_center import (
    GroupMatrix,
    GroupMatrixRow,
    NextBestAction,
    RoundCenterReadiness,
    RoundComparison,
    RoundDeviation,
    TeamRoundComparison,
    TradingWindowView,
    build_club_change_deviations,
    build_group_matrix,
    build_injury_deviations,
    build_missing_team_deviations,
    build_next_best_action,
    build_rank_deviations,
    build_round_center_readiness,
    build_round_comparison,
    build_round_deviations,
    build_rules_schedule_deviations,
    build_trading_window_view,
    select_round_deviations,
)
from .seasons import (
    SEASON_SCHEMA_VERSION,
    SeasonDefinition,
    SeasonStanding,
    SeasonStore,
    active_season_competitions,
    build_season_standings,
)
from .tournament import (
    DoubleEliminationMatch,
    DoubleEliminationTemplateConfig,
    GroupKnockoutTemplateConfig,
    LeagueTemplateConfig,
    SeedRule,
    SwissParticipant,
    SwissTemplateConfig,
    TournamentDefinition,
    TournamentPairing,
    TournamentTemplateConfig,
    SwissPairingConflict,
    build_swiss_participants,
    build_swiss_pairing_conflicts,
    TournamentTemplate,
    build_double_elimination_bracket,
    calculate_buchholz,
    create_tournament_definition,
    generate_league_fixtures,
    generate_group_stage_fixtures,
    generate_swiss_pairings,
    resolve_knockout_tie,
    tournament_standing_sort_key,
    tournament_template_config,
)
from .tournament_pairings import (
    PAIRING_SCHEMA_VERSION,
    TournamentPairingRevision,
    TournamentPairingStore,
    validate_tournament_pairing_revision,
)
from .version import VERSION

__all__ = [
    "VERSION",
    "AccountConfig", "AccountStore", "AppPaths", "FetchError", "GamePolicy",
    "GameUrl", "HoldetClient", "PathOverrides", "PayloadError", "PlayerEntry",
    "RosterEntry", "RoundStatus", "RoundSummary", "ScheduleRound", "ScrapedGame",
    "ScrapedTeam", "ScraperError",
    "TeamOverview", "TeamReference", "UnsupportedGameError", "UrlValidationError",
    "GroupDefinition", "GroupStore", "GroupTeam", "HubConfiguration", "ManagerGame",
    "TournamentConfig", "TournamentRevision", "TournamentState",
    "ManifestStore", "PlayerStatisticsIndex", "PlayerStatisticsStore",
    "RefreshManifest", "RefreshManifestStep", "RefreshMetadataChange",
    "SnapshotIndex", "SnapshotStore", "TeamSnapshot",
    "PlayerExportArtifact", "PlayerExportDocument", "PlayerExportStore",
    "PlayerStatisticsQuery", "TeamExportArtifact", "TeamExportDocument",
    "TeamExportStore", "build_player_export", "build_team_export",
    "build_standings", "build_tournament_head_to_head", "build_tournament_state",
    "DAILY_REFRESH_MAX_AGE", "RefreshMode", "RefreshPlan", "RefreshProgressCallback",
    "RefreshProgressEvent", "RefreshStep", "MetadataRefresh", "ManifestWriteError",
    "build_refresh_plan", "create_tournament_config", "filter_player_statistics", "normalize_game_url",
    "normalize_manager_game", "player_statistics_from_dict",
    "player_statistics_to_dict", "player_statistics_to_json", "refresh_game",
    "refresh_group", "refresh_manager_game", "resolve_paths", "serialize_player_export",
    "BackupManifest", "BackupManifestEntry", "BackupValidation",
    "RestoreResult", "DataQualityReport", "DataQualityRound", "HistoryPoint",
    "PlayerHistoryPoint", "PlayerSnapshotChange", "SnapshotDiff",
    "GameRefreshResult", "GroupRefreshResult", "PlayerRefresh", "TeamRefresh",
    "FIXTURE_CACHE_SCHEMA_VERSION", "FixtureRecord", "FixtureSnapshot",
    "FixtureSourceProfile", "FixtureStore",
    "TeamRankChange", "TeamSnapshotDiff", "GameMetadata", "GameMetadataStore",
    "HubSettings", "HubSettingsStore", "ManagerAlias", "WatchlistEntry",
    "HallOfFame", "HallOfFameEvent", "HallOfFamePlacement", "HallOfFameRow",
    "HallOfFameScoreProfile", "HallOfFameStore", "ScenarioPlayer",
    "TransferRuleProfile", "TransferScenario", "TransferValidation",
    "CYCLING_RULES", "FOOTBALL_RULES", "GOLF_RULES", "MOTOR_RULES",
    "UNKNOWN_RULES", "build_data_quality_report", "build_hall_of_fame",
    "build_history_series", "build_live_hall_of_fame_events",
    "build_player_history", "compare_round_snapshots", "compare_snapshots",
    "compare_team_rounds", "compare_team_snapshots", "create_backup",
    "create_backup_bytes", "game_metadata_from_context", "latest_snapshot_diff",
    "manager_identity_keys", "player_identity", "resolve_manager_identity",
    "restore_backup", "simulate_transfers", "transfer_rule_profile",
    "validate_backup", "watchlist_entry",

    "serialize_team_export", "team_export_data_package", "team_from_dict", "team_to_json",
]
__all__ += [
    "CalendarEvent", "ManagerCareer", "ManagerEvent", "ManagerHeadToHead",
    "ManagerProfile", "ManagerRating", "ManagerRoundResult", "RoundAward",
    "RoundStory", "RoundStoryFact", "RoundStoryTeamRef", "SeasonDefinition",
    "SeasonStanding", "SeasonStore",
    "TournamentDefinition", "TournamentPairing", "TournamentPairingRevision",
    "TournamentPairingStore", "TournamentTemplate", "SeedRule",
    "LeagueTemplateConfig", "SwissTemplateConfig",
    "GroupKnockoutTemplateConfig", "DoubleEliminationTemplateConfig",
    "DoubleEliminationMatch", "SwissParticipant", "HeadToHeadMeeting",
    "active_season_competitions", "build_calendar_events",
    "build_double_elimination_bracket", "build_manager_careers",
    "build_manager_head_to_head", "build_manager_ratings",
    "build_manager_round_results", "build_round_awards", "build_round_story",
    "build_season_standings", "calculate_buchholz",
    "build_swiss_participants",
    "create_tournament_definition", "generate_group_stage_fixtures", "generate_league_fixtures",
    "generate_swiss_pairings", "manager_events_from_hall_of_fame",
    "build_effective_manager_settings", "remap_manager_events",
    "GroupMatrix", "GroupMatrixRow", "NextBestAction",
    "RoundCenterReadiness", "RoundComparison", "RoundDeviation",
    "TeamRoundComparison", "TradingWindowView",
    "build_club_change_deviations", "build_group_matrix",
    "build_injury_deviations", "build_missing_team_deviations",
    "build_next_best_action", "build_rank_deviations",
    "build_round_center_readiness", "build_round_comparison",
    "build_round_deviations", "build_rules_schedule_deviations",
    "build_trading_window_view", "select_round_deviations",
    "SwissPairingConflict", "build_swiss_pairing_conflicts",
    "resolve_knockout_tie", "tournament_standing_sort_key",
    "TournamentTemplateConfig", "tournament_template_config",
    "validate_tournament_pairing_revision",
]
__all__ += ["validate_official_group_url"]
__all__ += [
    "ANALYSIS_INBOX_SCHEMA_VERSION", "AUDITED_RULE_PROFILES",
    "AnalysisCertainty", "AnalysisInboxStore", "AnalysisProvenance",
    "BankAnalysis", "CaptainAlternative", "CaptainAnalysis",
    "DEFAULT_PLAYER_TAGS", "ExposureRow", "GameRuleProfile",
    "GroupComparison", "GroupExposure", "IdealTeamResult",
    "OwnTeamSelection", "PlayerAnnotation", "PlayerDecisionAnalysis",
    "SavedPlayerFilter", "SimulationResult", "TeamDecisionLedger",
    "TransferDecision", "WatchlistAlert", "build_bank_analysis",
    "build_captain_analysis", "build_group_comparison",
    "build_group_exposure", "build_player_decision_analysis",
    "build_team_decision_ledger", "build_watchlist_alerts",
    "game_rule_from_dict", "game_rule_to_dict", "optimize_ideal_team",
    "parse_fixture_records", "player_query_from_dict", "rule_profile_for_game",
    "select_alert_baseline",
    "simulate_transfer_scenario",
]
__all__ += [
    "ANONYMIZATION_PROFILES", "DATA_PACKAGE_SCHEMA_VERSION",
    "INTEGRITY_INDEX_SCHEMA_VERSION", "LOCAL_API_DATASETS",
    "LOCAL_API_VERSION", "REPORT_SCHEMA_VERSION", "TABULAR_EXPORT_FORMATS",
    "ApiQueryError", "ArchiveResult", "CleanupCandidate", "DataPackage",
    "DataTable", "DatasetDefinition", "ImportOperation", "ImportPreview",
    "ImportResult", "IntegrityCheck", "IntegrityEntry", "IntegrityIssue",
    "IntegrityRepairPreview", "LocalDataApi", "RegisteredArtifact",
    "ReportArtifact", "ReportStore", "RetentionCandidate", "RetentionPlan",
    "SerializedPackage", "SportAdapter", "SportCapabilities",
    "StorageInventory", "StorageUsage", "anonymize_data_package",
    "apply_import", "archive_retention_candidates",
    "build_manager_game_report_package", "build_season_report_package",
    "build_storage_inventory", "build_support_bundle", "dataset_catalog",
    "delete_derived_files", "full_integrity_check", "get_sport_adapter",
    "list_cleanup_candidates", "neutralize_spreadsheet_text",
    "package_to_csv", "package_to_dict", "package_to_parquet",
    "package_to_xlsx", "plan_snapshot_retention", "preview_import",
    "preview_integrity_repair", "quick_integrity_check", "register_artifact",
    "registered_sport_adapters", "render_html_report",
    "render_round_story_html", "round_story_html_filename",
    "repair_integrity_index", "resolve_registered_artifact",
    "serialize_data_package", "table_to_csv", "player_export_data_package",
]
